### ISSUE TITLE
Passenger only allowing 487 connected clients?

### ISSUE THREAD

**Issue by mlangenberg** [dimelo/passenger-faye-issue#1]
After applying the fix, I encountered a low limit on the number of connected clients.

```
Connecting client 486 ... ok
Connecting client 487 ... 
```

Also can Passenger be used to spawn multiple workers under heavy load? (of course with Faye Redis backed) 

If not, what is the advantage over Thin?

**Comment by jarthod** [comment]
Hi, this is probably caused by the file descriptor limit, this should help:

### High concurrency tuning

For a highly concurrent setup, you'll have to tune your server.

Increase the global file descriptor limit in `/etc/sysctl.conf`:

    fs.file-max = 1000000

Reload config with `sudo sysctl -p`

Increase the file descriptor limit per process in `/etc/security/limits.conf`:

    *         hard    nofile      200000
    *         soft    nofile      200000
    root      hard    nofile      200000
    root      soft    nofile      200000

On some OS (at least Ubuntu 14.04) it is also required for this limits to be taken into account to edit `/etc/pam.d/common-session` and `/etc/pam.d/common-session-noninteractive` and add the following line to the end:

    session required pam_limits.so

Increase nginx connection and file descriptor limits in `/etc/nginx/nginx.conf`:

    worker_rlimit_nofile 65536;

    events {
      worker_connections 65536;
      multi_accept on;
    }

    http {
      tcp_nopush on;
      tcp_nodelay on;
    }

### (on MacOSX client for benchmark) Tune network TIME_WAIT

    # sysctl net.inet.tcp.msl
    net.inet.tcp.msl: 15000

    # sudo sysctl -w net.inet.tcp.msl=1000
    net.inet.tcp.msl: 15000 -> 1000

### (on client and server) Tune EventMachine

Event machine default are BAD and there is no autodetection, you need to set
them manually (this is already done in Faye-Server)

    EM.epoll
    EM.kqueue = true if EM.kqueue?
    EM.set_descriptor_table_size 500_000
    EM.set_max_timers 500_000
